# Generated by Django 2.2.10 on 2020-03-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='单位')),
            ],
            options={
                'verbose_name_plural': '单位',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='职务')),
            ],
            options={
                'verbose_name_plural': '职务',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('phone1', models.CharField(max_length=64, verbose_name='联系方式')),
                ('phone2', models.CharField(max_length=64, verbose_name='联系方式2')),
                ('Set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CS.Set', verbose_name='单位')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CS.Title', verbose_name='职务')),
            ],
            options={
                'verbose_name_plural': '保障专班',
            },
        ),
    ]
