# Generated by Django 2.2.10 on 2020-03-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone2',
            field=models.CharField(blank=True, max_length=64, verbose_name='联系方式2'),
        ),
    ]
