# Generated by Django 2.2.10 on 2020-03-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CIMSMain', '0009_channel_sign'),
        ('RC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='点名日期')),
            ],
            options={
                'verbose_name_plural': '点名情况',
            },
        ),
        migrations.CreateModel(
            name='RollType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='点名类型')),
            ],
            options={
                'verbose_name_plural': '点名情况',
            },
        ),
        migrations.RenameModel(
            old_name='Set',
            new_name='OrderSet',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='LocalChannel',
        ),
        migrations.AddField(
            model_name='rollcall',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CIMSMain.Channel', verbose_name='办会单位'),
        ),
        migrations.AddField(
            model_name='rollcall',
            name='roll_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RC.Type', verbose_name='点名类型'),
        ),
        migrations.AddField(
            model_name='rollcall',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='点名时间'),
        ),
    ]
