# Generated by Django 2.2.10 on 2020-03-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RC', '0002_auto_20200315_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'verbose_name_plural': '日常点名情况'},
        ),
        migrations.AlterModelOptions(
            name='rolltype',
            options={'verbose_name_plural': '点名级别'},
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='roll_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RC.RollType', verbose_name='点名类型'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
