# Generated by Django 2.2.10 on 2020-03-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RC', '0003_auto_20200315_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'verbose_name_plural': '日常点名'},
        ),
        migrations.AlterField(
            model_name='daily',
            name='datetime',
            field=models.DateField(verbose_name='点名日期'),
        ),
    ]
