# Generated by Django 2.2.10 on 2020-03-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RC', '0004_auto_20200315_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='channel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RC.RollCall', verbose_name='点名列表'),
        ),
    ]
