# Generated by Django 2.2.10 on 2020-03-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RC', '0005_daily_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='点名结果')),
            ],
            options={
                'verbose_name_plural': '点名结果',
            },
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CIMSMain.Channel', verbose_name='点名信道'),
        ),
        migrations.AddField(
            model_name='rollcall',
            name='order_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RC.OrderReturn', verbose_name='点名结果'),
        ),
    ]
