# Generated by Django 2.2.10 on 2020-03-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RC', '0007_auto_20200315_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='点名时间')),
            ],
            options={
                'verbose_name_plural': '点名时间',
            },
        ),
        migrations.RemoveField(
            model_name='daily',
            name='channel',
        ),
        migrations.AddField(
            model_name='rollcall',
            name='daily_record',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RC.Daily', verbose_name='第几天的点名'),
        ),
        migrations.AddField(
            model_name='rollcall',
            name='order_set',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RC.OrderSet', verbose_name='被点名人'),
        ),
        migrations.AddField(
            model_name='rollcall',
            name='remark',
            field=models.CharField(blank=True, max_length=512, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RC.RollChannel', verbose_name='点名信道'),
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='order_return',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RC.OrderReturn', verbose_name='点名结果'),
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='roll_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RC.RollType', verbose_name='点名类型'),
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='time',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RC.RollTime', verbose_name='点名时间'),
        ),
    ]
