# Generated by Django 2.2.10 on 2020-03-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RC', '0008_auto_20200316_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolltype',
            options={'verbose_name_plural': '点名类型'},
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='daily_record',
            field=models.DateField(blank=True, null=True, verbose_name='点名日期'),
        ),
        migrations.AlterField(
            model_name='rolltype',
            name='name',
            field=models.CharField(max_length=32, verbose_name='点名类型'),
        ),
        migrations.DeleteModel(
            name='Daily',
        ),
    ]
