# Generated by Django 2.2.10 on 2020-03-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='conferenceroom_name', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='avatar/%Y/%m/', verbose_name='form page')),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone1', models.CharField(max_length=64)),
                ('phone2', models.CharField(max_length=64)),
                ('office', models.ForeignKey(db_column='staff_office', on_delete=django.db.models.deletion.CASCADE, to='CIMSMain.Office')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='oset',
            field=models.ForeignKey(db_column='office_set', on_delete=django.db.models.deletion.CASCADE, to='CIMSMain.Set'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='meeting_name', max_length=128)),
                ('date', models.DateTimeField(db_column='meeting_time')),
                ('add_date', models.DateTimeField(db_column='add_date')),
                ('modify_date', models.DateTimeField(db_column='modify_date')),
                ('form_page', models.ForeignKey(db_column='form_page', on_delete=django.db.models.deletion.CASCADE, to='CIMSMain.FormPage')),
                ('from_level', models.ForeignKey(db_column='from_level', on_delete=django.db.models.deletion.CASCADE, related_name='fromlevel', to='CIMSMain.Level')),
                ('location', models.ForeignKey(db_column='conference_room', on_delete=django.db.models.deletion.CASCADE, to='CIMSMain.ConferenceRoom')),
                ('office', models.ForeignKey(db_column='office', on_delete=django.db.models.deletion.CASCADE, to='CIMSMain.Office')),
                ('staffs', models.ManyToManyField(to='CIMSMain.Staff')),
                ('to_level', models.ForeignKey(db_column='to_level', on_delete=django.db.models.deletion.CASCADE, related_name='tolevel', to='CIMSMain.Level')),
            ],
        ),
    ]
