# Generated by Django 2.2.10 on 2020-03-14 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CIMSMain', '0002_auto_20200313_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenceroom',
            options={'verbose_name_plural': '会议室'},
        ),
        migrations.AlterModelOptions(
            name='formpage',
            options={'verbose_name_plural': '申请表'},
        ),
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name_plural': '工作身份'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name_plural': '级别'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name_plural': '会议'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name_plural': '单位'},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'verbose_name_plural': '机关'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': '工作人员'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='add_date',
            field=models.DateTimeField(db_column='add_date', default=django.utils.timezone.now, verbose_name='创建条目日期'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, db_column='modify_date', verbose_name='最后修改日期'),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=64, verbose_name='机关'),
        ),
    ]
