# Generated by Django 2.2.10 on 2020-03-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIMSMain', '0003_auto_20200314_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, db_column='add_date', verbose_name='创建条目日期'),
        ),
    ]
