# Generated by Django 2.2.10 on 2020-03-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CIMSMain', '0005_auto_20200314_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='省级信道')),
            ],
            options={
                'verbose_name_plural': '省级信道',
            },
        ),
        migrations.CreateModel(
            name='LocalChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='市级信道')),
            ],
            options={
                'verbose_name_plural': '市级信道',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='channel',
            field=models.ForeignKey(blank=True, db_column='channel', null=True, on_delete=django.db.models.deletion.CASCADE, to='CIMSMain.Channel', verbose_name='省级会议信道'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='local_channel',
            field=models.ForeignKey(blank=True, db_column='local_channel', null=True, on_delete=django.db.models.deletion.CASCADE, to='CIMSMain.LocalChannel', verbose_name='市级会议信道'),
        ),
    ]
