# Generated by Django 2.2.10 on 2020-03-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIMSMain', '0006_auto_20200314_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='channel',
        ),
        migrations.AddField(
            model_name='meeting',
            name='channel',
            field=models.ManyToManyField(blank=True, db_column='channel', null=True, to='CIMSMain.Channel', verbose_name='省级会议信道'),
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='local_channel',
        ),
        migrations.AddField(
            model_name='meeting',
            name='local_channel',
            field=models.ManyToManyField(blank=True, db_column='local_channel', null=True, to='CIMSMain.LocalChannel', verbose_name='市级会议信道'),
        ),
    ]
