# Generated by Django 2.2.10 on 2020-03-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIMSMain', '0008_auto_20200314_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='sign',
            field=models.CharField(blank=True, max_length=64, verbose_name='标志'),
        ),
    ]
