# Generated by Django 2.2.10 on 2020-04-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIMSMain', '0010_auto_20200401_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_status',
        ),
    ]
