# Generated by Django 2.2.10 on 2020-04-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CIMSMain', '0011_remove_meeting_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_status',
            field=models.ForeignKey(db_column='meeting_status', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meetingstatus', to='CIMSMain.MeetingStatus', verbose_name='会议状态'),
        ),
    ]
