# Generated by Django 2.2.10 on 2020-04-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIMSMain', '0012_meeting_meeting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='会议类型')),
            ],
            options={
                'verbose_name_plural': '会议类型',
            },
        ),
    ]
