# Generated by Django 2.2.10 on 2020-04-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIMSMain', '0013_meetingcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcategory',
            name='remark',
            field=models.CharField(default='', max_length=256, verbose_name='备注'),
        ),
    ]
