# Generated by Django 2.2.10 on 2020-04-01 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CIMSMain', '0014_meetingcategory_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_category',
            field=models.ForeignKey(db_column='meeting_category', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meetingcategory', to='CIMSMain.MeetingCategory', verbose_name='会议类型'),
        ),
    ]
