# Generated by Django 2.2.10 on 2020-04-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIMSMain', '0015_meeting_meeting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='remark',
            field=models.CharField(db_column='meeting_remark', default='', max_length=256, null=True, verbose_name='备注'),
        ),
    ]
